### ISSUE TITLE
Jquery 3.0 issues

### ISSUE THREAD

**Issue by adameska** [uxsolutions/bootstrap-datepicker#2039]
Turns out if have https://vitalets.github.io/x-editable/ installed this control doesn't work. Code this styling be namespaced to prevent that?

**Comment by acrobat** [comment]
@adameska can you provide a jsfiddle example to show the exact problem?

**Comment by adameska** [comment]
https://jsfiddle.net/uymqbp35/

**Comment by vsn4ik** [comment]
@adameska Use Bootstrap v3.3.7

**Comment by Azaret** [comment]
Hi,

There is nothing we can do on our hand, [x-editable does override our rules on purporse](https://github.com/vitalets/x-editable/blob/master/src/inputs/date/bootstrap-datepicker/css/datepicker.css).
Note that it use a very old version of the datepicker (`1.1.2`), even a pre-eternicode era I think.
Since x-editable looks like no more maintened anymore, I recommend you to bump an updated version of the datepicker on the sources of x-editable and look for changes to do if you can.
If you can't, I'm afraid we cannot do much to help you.
