### ISSUE TITLE
Including time in the date picker?

### ISSUE THREAD

**Issue by jmccormac01** [uxsolutions/bootstrap-datepicker#2073]
Is it possible to include the current time in the date picker. I know it is a *date*picker but having a time option would be great also.

**Comment by professorNim** [comment]
+1

Came here looking for an issue already opened or to open my own for this exact reason. Seems there are a number of datepickers out there (this one being my favorite), and only a limited number of time pickers.

**Comment by acrobat** [comment]
Thanks for you interest in the time picking feature. We currently don't support time picking and unfortunately due to limited time and resources I don't see this feature being added any time soon. 

If you really need an all in one datetimepicker you should check [Eonasdan/bootstrap-datetimepicker ](https://github.com/Eonasdan/bootstrap-datetimepicker)
