### ISSUE TITLE
[Question] Is this better than Eonasdan/bootstrap-datetimepicker ?

### ISSUE THREAD

**Issue by ajcastro** [uxsolutions/bootstrap-datepicker#2196]
Is this better than https://github.com/Eonasdan/bootstrap-datetimepicker?

**Comment by acrobat** [comment]
I don't think the question is which lib is better but which features do you need. The 2 libs have diverged quite far feature wise so the choice is up to you. If you need the ability to allow the users to select a time with the date you will need the Eonasdan/bootstrap-datetimepicker.

Otherwise you will just have to compare the features of each library.
