### ISSUE TITLE
Date range selection only works backwards

### ISSUE THREAD

**Issue by fracet** [uxsolutions/bootstrap-datepicker#2246]
Hi
I am trying to add a date range picker to my application and noticed a weird behaviour, which also appears on the demo site.

### Expected behaviour
When selecting a date range, I would expect to select the start date first, and then the end date to complete the selection of the range.

### Actual behaviour
The range selection only works if I go backwards. For instance, if I try to select a range from the 8th to the 12th, I click on the "8" first and that sets the start date. If I then click the "12", it sets the 12 as the new start date, rather than as the end date of the range. If I then click on the "8" again, the range is successfully set to 8-12 (i.e. the 12 finally becomes the end-date).

This issue only appears in the calendar that opens when clicking on the "start date" field. The calendar in the "End-date" field works correctly. However, I would expect them to both work the same way.

### Datepicker version used

latest

### Example code

Jsfiddle example to reproduce the problem.

**Comment by didiatworkz** [comment]
Still relevant!

**Comment by karahan** [comment]
I have this same problem, did you find any solutions? @didiatworkz @fracet

**Comment by trevrobwhite** [comment]
I have a start and an end date, the end works like the start and start works like the end, I'm not sure how to reverse them, if you click on the end date does it work correctly?

**Comment by Azaret** [comment]
Hi,
You're not using the range component as expected actually.

The range component only provide a quick way to link 2 datepickers to each others. On the demo page, when you select the range component, you'll see that there is 2 inputs, the first one opens the start datepicker and the second one opens the end datepicker.

What's happening that confuse you is that when selecting a start date after the end date, or a end date before the start date, or if one of the two is not selected yet, then it will select the same date for both (you can see the values in the inputs changing likewise).
So when you select the 12th, it will set both the start date and the end date to 12th, then as you're using only the start datepicker, when selecting the 8th it will select the 8th as the start date while keeping the 12th as the end date.

So yeah, this is intended because it use two datepicker, and I would suggest two datepicker for an UX standpoint as it is less cumbersome for user to manipulate a date range, unless you provide drag/drop at range edges which this do not.

**Comment by benjaminchan66** [comment]
You can use this
keepEmptyValues: true
