### ISSUE TITLE
selecting date with enter key not working when forceParse is false

### ISSUE THREAD

**Issue by benjaminkomen** [uxsolutions/bootstrap-datepicker#2381]
### Expected behaviour
The date should be selected when pressing the ENTER key, regardless of the setting of forceParse.

### Actual behaviour
The date is only selected when pressing ENTER, when forceParse is set to true (its default value).

### Datepicker version used
1.8.0

### Additional comment
On line 1455 in bootstrap-datepicker.js the code:
```
case 13: // enter
	if (!this.o.forceParse)
		break;
```
should be changed, because now it forces you to have forceParse to be true, to not break out of the case expression.

**Comment by petr-kolinek** [comment]
Definitely not expected behaviour!

I would expect the `forceParse ` option to be considered only when working directly with the input like pasting/writing value manually. 
Pressing the enter key is (from my point of view) the same action as clicking on the day within the component.

It is also **not documented** and I had to debug the code in order to find out what is happening and why.

**Comment by SeanKendleAtThornburg** [comment]
Why was this closed?? Bug still exists.
