### ISSUE TITLE
input field validation with backbone forms.

### ISSUE THREAD

**Issue by szymdzum** [uxsolutions/bootstrap-datepicker#951]
I have a problem with validating empty input in a form. I'm using backbone forms and validation on blur.
Datepicker config is:

```
this.$el.datepicker({
                startView: 2,
                autoclose: true,
                format: 'dd-mm-yyyy'
                });
```

So when the calendar opens and I start selecting the year the input loses focus and validates as empty field. The validator: 

```
 var emptyDate = function(value) {
err = { message: 'Wybierz datę.' };
if (value.length === 0) return err;
 };
```

Datepicker code:

```
    Backbone.Form.editors.DatePicker = Backbone.Form.editors.Text.extend({
        initialize: function(options) {
            Backbone.Form.editors.Text.prototype.initialize.call(this, options);
            this.$el.addClass('datepicker input-small-custom');
            this.$el.datepicker({
                startView: 2,
                autoclose: true,
                format: 'dd-mm-yyyy'
                });

                this.on('blur',function(){      
                this.form.fields[options.key].validate();       
            });
            },
        getValue: function() {
                var value = this.$el.val();        
                return value;
            },      
        render: function() {
                Backbone.Form.editors.Text.prototype.render.apply(this, arguments);
                this.$el.datepicker({});
                return this;
            } 
});
```

Any idea how to tell the validator to wait with validation untill the calendar is closed ?

**Comment by lphooge** [comment]
I have a similar problem with jquery-validation. 

The cause is that the date input field loses focus when the mousedown event on a date in the picker happens. But the date is only later changed whe the click event happens (mouse button was released again).

So the validator will validate the old value, before it is changed.

I now use the following workaround to supress the original focusout event and trigger it manually when the date was actually changed.

$('#mydatepicker').datepicker()
.on('changeDate clearDate', function(e){
  $(this).trigger('focusout', true);
})
.bind("focusout", function(e, is_changeDate){
  if(!is_changeDate){
    e.stopPropagation();
  }
});

**Comment by gorillapower** [comment]
@lphooge Thank you! Just what I was looking for.
